# Copyright 2021 Ubuntu
# See LICENSE file for licensing details.
#

options:
  "external_url":
    "type": "string"
    "description": "The FQDN for your GitLab unit"
    "default": !!null ""
  "http_port":
    "type": "string"
    "description": "The HTTP port"
    "default": "80"
  tls_secret_name:
    type: string
    description: "The Kubernetes TLS secret resource name."
    default: ""
